### ISSUE TITLE
The missing imageFeature.pkl and test.pkl raise an error

### ISSUE THREAD

**Issue by zxzhou9** [harshm121/ClipVQA#2]
I find the code
'''
                 if(os.path.exists(pklFilePath)):
			allFeatures = pkl.load(open(pklFilePath, 'rb'))
		else:
			allFeatures = {}
'''
while it causes the error "No such file or directory: 'COCO_val2014xxxxx'

So, I think I should still put an existed .pkl file here, where can I get the two file?

**Comment by harshm121** [comment]
We store the precomputed image features for zero shot testing. Please refer to [this](https://github.com/harshm121/ClipVQA/blob/cfa5e26ca988c5b8b9d15623fd1d264ec51432fe/appendModelGetResults.py#L29) and [this](https://github.com/harshm121/ClipVQA/blob/cfa5e26ca988c5b8b9d15623fd1d264ec51432fe/CLIPInterface/clipInterface.py#L159)

**Comment by zxzhou9** [comment]
got that! Thank u so much!
